module: Listable
title: Listable

github_url: https://github.com/kyleve/Listable

skip_undocumented: false

output: /docs

theme: fullwidth
# TODO: to enable this, first rename docs whose names conflict with symbols
# documentation: Documentation/**/*.md

# custom_categories:
#   - name: Creating Custom Elements
#     children:
#     - Element
#     - ProxyElement
#     - ElementContent
#     - ViewDescription
#     - LayoutTransition
#     - VisibilityTransition
#   - name: Displaying Elements
#     children:
#     - BlueprintView
#     - ElementPreview
#   - name: Common Elements
#     children:
#     - AccessibilityBlocker
#     - AccessibilityContainer
#     - AccessibilityElement
#     - AdaptedEnvironment
#     - EnvironmentReader
#     - Aligned
#     - AttributedLabel
#     - Box
#     - Button
#     - Centered
#     - Column
#     - ConstrainedAspectRatio
#     - ConstrainedSize
#     - Empty
#     - EqualStack
#     - GeometryReader
#     - Image
#     - Inset
#     - Label
#     - Overlay
#     - Row
#     - Rule
#     - ScrollView
#     - SegmentedControl
#     - Spacer
#     - Tappable
#     - TextField
#     - TransitionContainer
#   - name: Environment
#     children:
#     - Environment
#     - EnvironmentKey
# custom_categories_unlisted_prefix: ''